export const EXERCISES = [
  {
    id: 0,
    title: "왼쪽 어깨 스트레칭",
    subtitle: "어깨를 유연하게 해줍니다",
    description: "",
    image: "/assets/left-shoulderStretching.png",
    pose: "",
  },
  {
    id: 1,
    title: "오른쪽 어깨 스트레칭",
    subtitle: "어깨를 유연하게 해줍니다",
    description: "",
    image: "/assets/legStretching.png",
    pose: "",
  },
  {
    id: 2,
    title: "왼쪽 허리 스트레칭",
    subtitle: "허리를 유연하게 해줍니다",
    description: "",
    image: "/assets/waistStretching.png",
    pose: "",
  },
  {
    id: 3,
    title: "오른쪽 허리 스트레칭",
    subtitle: "허리를 유연하게 해줍니다",
    description: "",
    image: "/assets/waistStretching.png",
    pose: "",
  },
  {
    id: 4,
    title: "다리 스트레칭",
    subtitle: "허리를 굽혀 스트레칭합니다",
    description: "",
    image: "/assets/legStretching2.png",
    pose: "",
  },
  {
    id: 5,
    title: "팔굽혀펴기",
    subtitle: "근력 및 근지구력을 향상합니다",
    description: "",
    image: "/assets/pushup.png",
    pose: "",
  },
  {
    id: 6,
    title: "덤벨 상체운동",
    subtitle: "기구를 사용한 근력 운동입니다",
    description: "",
    image: "/assets/dumbellupper.png",
    pose: "",
  },
  {
    id: 7,
    title: "밴드 상체운동",
    subtitle: "기구를 사용한 근력 운동입니다",
    description: "",
    image: "/assets/bandupper.png",
    pose: "",
  },
];
