export const EXERCISES = [
  {
    id: 0,
    title: "왼쪽 어깨 스트레칭",
    subtitle: "어깨를 유연하게 해줍니다",
    description: "",
    image: "/assets/stretchings/left-shoulder-stretching.png",
    pose: "",
  },
  {
    id: 1,
    title: "오른쪽 어깨 스트레칭",
    subtitle: "어깨를 유연하게 해줍니다",
    description: "",
    image: "/assets/stretchings/right-shoudler-stretching.png",
    pose: "",
  },
  {
    id: 2,
    title: "왼쪽 허리 스트레칭",
    subtitle: "허리를 유연하게 해줍니다",
    description: "",
    image: "/assets/stretchings/left-waist-stretching.png",
    pose: "",
  },
  {
    id: 3,
    title: "오른쪽 허리 스트레칭",
    subtitle: "허리를 유연하게 해줍니다",
    description: "",
    image: "/assets/stretchings/right-waist-stretching.png",
    pose: "",
  },
  {
    id: 4,
    title: "다리 스트레칭",
    subtitle: "허리를 굽혀 스트레칭합니다",
    description: "",
    image: "/assets/stretchings/leg-stretching.png",
    pose: "",
  },
  {
    id: 5,
    title: "팔굽혀펴기",
    subtitle: "근력 및 근지구력을 향상합니다",
    description: [
      "첫째, 양 손 사이를 어깨 너비만큼 벌려 바닥을 짚는다.",
      "둘째, 머리에서 발 끝까지 일직선을 이룬 상태로 팔을 이용해 몸을 내린다.",
      "셋째, 머리에서 발 끝까지 일직선을 이룬 상태로 팔을 이용해 몸을 올린다.",
    ],
    image: "/assets/exercises/push-up.png",
    pose: "PushUp",
  },
  {
    id: 6,
    title: "덤벨 상체운동",
    subtitle: "기구를 사용한 근력 운동입니다",
    description: [
      "첫째, 양 팔에 덤벨을 들고 바로 선다.",
      "둘째, 몸의 반동, 팔꿈치의 움직임을 최소화하여 덤벨을 들어올린다.",
      "셋째, 몸의 반동, 팔꿈치의 움직임을 최소화하여 덤벨을 내린다.",
    ],
    image: "/assets/exercises/dumbbell-upper.png",
    pose: "DumbbellUpper",
  },
  {
    id: 7,
    title: "밴드 상체운동",
    subtitle: "기구를 사용한 근력 운동입니다",
    description: [
      "첫째, 밴드 가운데를 발로 밟는다",
      "둘째, 팔꿈치를 살짝 구부린 상태로 어깨 높이만큼 들어올려준다.",
    ],
    image: "/assets/exercises/band-upper.png",
    pose: "BandUpper",
  },
];
